version: '3'
services:
  redis:
    container_name: queue-redis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - app_network

volumes:
  redis_data:

networks:
  app_network:
    driver: bridge